services:
  db:
    image: postgres:16
    container_name: flicklog-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flicklog
    ports:
      - '5432:5432'
    volumes:
      - flicklog-data:/var/lib/postgresql/data

volumes:
  flicklog-data:
